# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3

# Mod properties
mod_version=1.0.0
maven_group=net.lusik21556
archives_base_name=rankedsmp

# Dependencies
fabric_version=0.141.5+1.21.11
